name: Push Event Workflow

on:
  push:
    branches-ignore:
      - main

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: 'latest'
      - name: Execute CLI command
        run: |
          trunk build