name: Push Event Workflow

on:
  push:

# Make sure CI fails on all warnings, including Clippy lints
env:
  RUSTFLAGS: "-Dwarnings"
  AWS_DEFAULT_REGION: "us-west-2"
  S3_BUCKET: "yew-ascii-generator"


jobs:
  build_and_test:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features
      - name: Install Trunk
        run: |
          cargo install trunk
      - name: Adding wasm core
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Trunk build
        run: |
          trunk build
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
      - name: Deploy files to S3 bucket
        if: github.event.pull_request.merged == true
        run: aws s3 sync ./dist/ s3://${{ env.S3_BUCKET }} --delete